# .zprofile is for login shells. It is basically the same as .zlogin except that it's sourced before .zshrc whereas .zlogin is sourced after .zshrc. According to the zsh documentation, ".zprofile is meant as an alternative to .zlogin for ksh fans; the two are not intended to be used together, although this could certainly be done if desired."

# Homebrew
[ -f "/usr/local/bin/brew" ] && eval $(/usr/local/bin/brew shellenv) # for Intel Macs
[ -f "/opt/homebrew/bin/brew" ] && eval $(/opt/homebrew/bin/brew shellenv) # for Apple Silicon Macs

# For zsh completions
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

## SSH auto completion ##
# Highlight the current autocomplete option
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Better SSH/Rsync/SCP Autocomplete
zstyle ':completion:*:(scp|rsync):*' tag-order ' hosts:-ipaddr:ip\ address hosts:-host:host files'
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-host' ignored-patterns '*(.|:)*' loopback ip6-loopback localhost ip6-localhost broadcasthost
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-ipaddr' ignored-patterns '^(<->.<->.<->.<->|(|::)([[:xdigit:].]##:(#c,2))##(|%*))' '127.0.0.<->' '255.255.255.255' '::1' 'fe80::*'

# Allow for autocomplete to be case insensitive
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' \
  '+l:|?=** r:|?=**'

#export PYENV_ROOT="$HOME/.pyenv"
#command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"

## Python Stuff ##
# For python virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=$(pyenv which python3)
# Sets the location where the virtual environments should live, the location of your development project directories, and the location of the script installed with this package.
export WORKON_HOME=$HOME/.virtualenvs #virtual environment directory
mkdir -p $WORKON_HOME     #make a virtual environment directory, if one does not already exist.
export PROJECT_HOME=$HOME/Developer/Projects #project working directories
/Users/hcbowman/.pyenv/shims/virtualenvwrapper.sh
export PYENV_ROOT="$HOME/.pyenv"

command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Use export GPG_TTY=$TTY, works anywhere and it’s faster. TTY is a special parameter set by Zsh very early during initialization. It gives you access to the terminal even when stdin might be redirected.
export GPG_TTY=$TTY


# DEBUG
#echo ".zprofile ran"
