# .zshenv(this file) → .zprofile → .zshrc → .zlogin → .zlogout
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share


#. "$HOME/.cargo/env"

# DEBUG
#echo ".zshenv ran"